### ISSUE TITLE
Error: Parsing git branch name

### ISSUE THREAD

**Issue by HoughIO** [launchdarkly/find-code-references#1]
Hey y'all!

Excited to move my current github actions to the new YAML format! Although I think I ran into a bug in this action...

My current YAML for github actions looks like this

```YAML
on: push
name: Launch Darkly References Check
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LD_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
        LD_PROJ_KEY: default
```

Which seems to be in alignment with the README, but on run I seem to get an error every time...

```BASH
/usr/bin/docker run --name b3e3f70048f4234f874e5cb2d49457b881c1a2_aa989a --label b3e3f7 --workdir /github/workspace --rm -e GITHUB_TOKEN -e LD_ACCESS_TOKEN -e LD_PROJ_KEY -e INPUT_LD-PROJ-KEY -e INPUT_LD-ACCESS-TOKEN -e INPUT_GITHUB-TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/REPO/REPO":"/github/workspace" b3e3f7:0048f4234f874e5cb2d49457b881c1a2
 INFO: 2019/08/12 17:09:12 github-actions.go:24: Setting GitHub action env vars
INFO: 2019/08/12 17:09:12 github-actions.go:60: starting repo parsing program with options:
 map[defaultBranch:master repoUrl:https://github.com/ORG/REPO delimiters: exclude: baseUri: debug:false repoType:github repoName:REPO dir:/github/workspace updateSequenceId:1565629698000 accessToken: projKey:KEY contextLines:2]
INFO: 2019/08/12 17:09:12 command.go:191: absolute directory path: /github/workspace
ERROR: 2019/08/12 17:09:12 coderefs.go:66: error parsing git branch name: git repo at /github/workspace must be checked out to a valid branch
##[error]Docker run failed with exit code 1
```

I'm guessing this has to do with the move from static directories `/github/workspace` to env vars `$GITHUB_WORKSPACE`.

Any thoughts?

**Comment by HoughIO** [comment]
Although taking another look at this, the new format requires the codebase to be cloned with the `actions/checkout@v1` action located [here](https://github.com/actions/checkout). Which seems to not be a specific branch, but checks out the ref based on the pull request data sent in the payload.

**Comment by vlymar** [comment]
Hi @HoughIO, thanks for the report. We were internally aware of this issue but dropped the ball on addressing it.

As you've already determined, github actions v2 contains a breaking change. v1 cloned the repo into the action container and checked it out to the correct branch. v2 removes this functionality and asks the user to manually include the `actions/checkout` step. Unfortunately that action leaves the repo in a detached head state rather than checked out to a branch, like in v1.

The fix is simple - we need `ld-find-code-refs` to read the branch name from `$GITHUB_REF` rather than try to get it from `git` as we do now. Until we make that change, there is a hacky workaround for getting this v2 action to work. You could add the following action in between `actions/checkout` and the code references action:

```
- name: Prepare repository
  run: git checkout "${GITHUB_REF:11}"
```

This just gets the repo out of the detached head state so the current version of ld-find-code-refs can run.

My recommendation would be to wait on using this v2 action until we have shipped v2 compatibility to `ld-find-code-refs`. I will post again to this issue when that is done.

Thanks, and apologies for the trouble.

**Comment by victorquinn** [comment]
`${GITHUB_REF:11}`? is that a typo or is that really what's needed?

**Comment by HoughIO** [comment]
That's a good hack!
`GITHUB_REF`
>The branch or tag ref that triggered the workflow. For example, `refs/heads/feature-branch-1`. If neither a branch or tag is available for the event type, the variable will not exist.
--

So it would be the current branch!
Neat!

**Comment by vlymar** [comment]
> ${GITHUB_REF:11}? is that a typo or is that really what's needed?

Sadly it is not a typo 😄 . It's a bash trick for string manipulation, basically says "return `$GITHUB_REF` starting at character position 11 (trims off `refs/heads/`)"

I'm currently working on first class support for Github actions v2 for ld-find-code-refs, so I'd recommend waiting for that to land. I expect to have it ready this week.

**Comment by HoughIO** [comment]
You're a beast!
Thanks for your support!

**Comment by victorquinn** [comment]
Slick!

**Comment by vlymar** [comment]
This issue is fixed in the [`v2` release](https://github.com/launchdarkly/find-code-references/releases/tag/v2) of `find-code-references`.

If you update your workflows to `uses: launchdarkly/find-code-references@v2` things should just work.

Thanks for the reports!
